#!/bin/bash

files=(
microsoftoffice.part001.rar
microsoftoffice.part002.rar
microsoftoffice.part003.rar
microsoftoffice.part004.rar
microsoftoffice.part005.rar
microsoftoffice.part006.rar
microsoftoffice.part007.rar
microsoftoffice.part008.rar
microsoftoffice.part009.rar
microsoftoffice.part010.rar
microsoftoffice.part011.rar
microsoftoffice.part012.rar
microsoftoffice.part013.rar
microsoftoffice.part014.rar
microsoftoffice.part015.rar
microsoftoffice.part016.rar
microsoftoffice.part017.rar
microsoftoffice.part018.rar
microsoftoffice.part019.rar
microsoftoffice.part020.rar
microsoftoffice.part021.rar
microsoftoffice.part022.rar
microsoftoffice.part023.rar
microsoftoffice.part024.rar
microsoftoffice.part025.rar
microsoftoffice.part026.rar
microsoftoffice.part027.rar
microsoftoffice.part028.rar
microsoftoffice.part029.rar
microsoftoffice.part030.rar
microsoftoffice.part031.rar
microsoftoffice.part032.rar
microsoftoffice.part033.rar
microsoftoffice.part034.rar
microsoftoffice.part035.rar
microsoftoffice.part036.rar
microsoftoffice.part037.rar
microsoftoffice.part038.rar
microsoftoffice.part039.rar
microsoftoffice.part040.rar
microsoftoffice.part041.rar
microsoftoffice.part042.rar
microsoftoffice.part043.rar
microsoftoffice.part044.rar
microsoftoffice.part045.rar
microsoftoffice.part046.rar
microsoftoffice.part047.rar
microsoftoffice.part048.rar
microsoftoffice.part049.rar
microsoftoffice.part050.rar
microsoftoffice.part051.rar
microsoftoffice.part052.rar
microsoftoffice.part053.rar
microsoftoffice.part054.rar
microsoftoffice.part055.rar
microsoftoffice.part056.rar
microsoftoffice.part057.rar
microsoftoffice.part058.rar
microsoftoffice.part059.rar
microsoftoffice.part060.rar
microsoftoffice.part061.rar
microsoftoffice.part062.rar
microsoftoffice.part063.rar
microsoftoffice.part064.rar
microsoftoffice.part065.rar
microsoftoffice.part066.rar
microsoftoffice.part067.rar
microsoftoffice.part068.rar
microsoftoffice.part069.rar
microsoftoffice.part070.rar
microsoftoffice.part071.rar
microsoftoffice.part072.rar
microsoftoffice.part073.rar
microsoftoffice.part074.rar
microsoftoffice.part075.rar
microsoftoffice.part076.rar
microsoftoffice.part077.rar
microsoftoffice.part078.rar
microsoftoffice.part079.rar
microsoftoffice.part080.rar
microsoftoffice.part081.rar
microsoftoffice.part082.rar
microsoftoffice.part083.rar
microsoftoffice.part084.rar
microsoftoffice.part085.rar
microsoftoffice.part086.rar
microsoftoffice.part087.rar
microsoftoffice.part088.rar
microsoftoffice.part089.rar
microsoftoffice.part090.rar
microsoftoffice.part091.rar
microsoftoffice.part092.rar
microsoftoffice.part093.rar
microsoftoffice.part094.rar
microsoftoffice.part095.rar
microsoftoffice.part096.rar
microsoftoffice.part097.rar
microsoftoffice.part098.rar
microsoftoffice.part099.rar
microsoftoffice.part100.rar
microsoftoffice.part101.rar
microsoftoffice.part102.rar
microsoftoffice.part103.rar
microsoftoffice.part104.rar
microsoftoffice.part105.rar
microsoftoffice.part106.rar
microsoftoffice.part107.rar
microsoftoffice.part108.rar
microsoftoffice.part109.rar
microsoftoffice.part110.rar
microsoftoffice.part111.rar
microsoftoffice.part112.rar
microsoftoffice.part113.rar
microsoftoffice.part114.rar
microsoftoffice.part115.rar
microsoftoffice.part116.rar
microsoftoffice.part117.rar
microsoftoffice.part118.rar
microsoftoffice.part119.rar
microsoftoffice.part120.rar
microsoftoffice.part121.rar
microsoftoffice.part122.rar
microsoftoffice.part123.rar
microsoftoffice.part124.rar
microsoftoffice.part125.rar
microsoftoffice.part126.rar
microsoftoffice.part127.rar
microsoftoffice.part128.rar
microsoftoffice.part129.rar
microsoftoffice.part130.rar
microsoftoffice.part131.rar
microsoftoffice.part132.rar
microsoftoffice.part133.rar
microsoftoffice.part134.rar
microsoftoffice.part135.rar
microsoftoffice.part136.rar
microsoftoffice.part137.rar
microsoftoffice.part138.rar
microsoftoffice.part139.rar
microsoftoffice.part140.rar
microsoftoffice.part141.rar
microsoftoffice.part142.rar
microsoftoffice.part143.rar
microsoftoffice.part144.rar
microsoftoffice.part145.rar
microsoftoffice.part146.rar
microsoftoffice.part147.rar
microsoftoffice.part148.rar
microsoftoffice.part149.rar
microsoftoffice.part150.rar
microsoftoffice.part151.rar
microsoftoffice.part152.rar
microsoftoffice.part153.rar
microsoftoffice.part154.rar
microsoftoffice.part155.rar
microsoftoffice.part156.rar
microsoftoffice.part157.rar
microsoftoffice.part158.rar
microsoftoffice.part159.rar
microsoftoffice.part160.rar
microsoftoffice.part161.rar
microsoftoffice.part162.rar
microsoftoffice.part163.rar
microsoftoffice.part164.rar
microsoftoffice.part165.rar
microsoftoffice.part166.rar
microsoftoffice.part167.rar
microsoftoffice.part168.rar
microsoftoffice.part169.rar
microsoftoffice.part170.rar
microsoftoffice.part171.rar
microsoftoffice.part172.rar
microsoftoffice.part173.rar
microsoftoffice.part174.rar
microsoftoffice.part175.rar
microsoftoffice.part176.rar
microsoftoffice.part177.rar
microsoftoffice.part178.rar
microsoftoffice.part179.rar
microsoftoffice.part180.rar
microsoftoffice.part181.rar
microsoftoffice.part182.rar
microsoftoffice.part183.rar
microsoftoffice.part184.rar
microsoftoffice.part185.rar
microsoftoffice.part186.rar
microsoftoffice.part187.rar
microsoftoffice.part188.rar
microsoftoffice.part189.rar
microsoftoffice.part190.rar
microsoftoffice.part191.rar
microsoftoffice.part192.rar
microsoftoffice.part193.rar
microsoftoffice.part194.rar
microsoftoffice.part195.rar
microsoftoffice.part196.rar
microsoftoffice.part197.rar
microsoftoffice.part198.rar
microsoftoffice.part199.rar
microsoftoffice.part200.rar
microsoftoffice.part201.rar
microsoftoffice.part202.rar
microsoftoffice.part203.rar
microsoftoffice.part204.rar
microsoftoffice.part205.rar
microsoftoffice.part206.rar
microsoftoffice.part207.rar
microsoftoffice.part208.rar
microsoftoffice.part209.rar
microsoftoffice.part210.rar
microsoftoffice.part211.rar
microsoftoffice.part212.rar
microsoftoffice.part213.rar
microsoftoffice.part214.rar
microsoftoffice.part215.rar
microsoftoffice.part216.rar
microsoftoffice.part217.rar
microsoftoffice.part218.rar
microsoftoffice.part219.rar
microsoftoffice.part220.rar
microsoftoffice.part221.rar
microsoftoffice.part222.rar
microsoftoffice.part223.rar
microsoftoffice.part224.rar
microsoftoffice.part225.rar
microsoftoffice.part226.rar
microsoftoffice.part227.rar
microsoftoffice.part228.rar
microsoftoffice.part229.rar
microsoftoffice.part230.rar
microsoftoffice.part231.rar
microsoftoffice.part232.rar
microsoftoffice.part233.rar
microsoftoffice.part234.rar
microsoftoffice.part235.rar
microsoftoffice.part236.rar
microsoftoffice.part237.rar
microsoftoffice.part238.rar
microsoftoffice.part239.rar
microsoftoffice.part240.rar
microsoftoffice.part241.rar
microsoftoffice.part242.rar
microsoftoffice.part243.rar
microsoftoffice.part244.rar
microsoftoffice.part245.rar
microsoftoffice.part246.rar
microsoftoffice.part247.rar
microsoftoffice.part248.rar

)


cmd_git_add_commit_push()
{
    local filename=$1

    git add $filename
    git commit -m "$filename"
    git push origin master
    rm -fr $filename

}

cmd_github_upload()
{
    local skip_num=0;
    local num=0

    for filename in "${files[@]}";do
        let "num=num+1"
        echo
        echo
        echo $filename
        echo "num=$num";
        if [[ $num -le $skip_num ]];then
            echo "skip"
            continue
        fi

				cmd_git_add_commit_push $filename

        date

    done

}

cmd_github_upload

